server:
  port: 8082
  servlet:
    context-path: /api

# TCP Server Configuration
tcp:
  server:
    port: 8083
    timeout: 30000

spring:
  application:
    name: vibechat-backend
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:vibechat
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    jwt:
      secret: vibechat-secret-key-2024
      expiration: 864000000  # 10 days in milliseconds

  mail:
    host: 127.0.0.1
    port: 1025
    username: toreythegizzler@pm.me
    password: FTBGxYxABQPh4MArikvsyw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

logging:
  level:
    com.vibechat: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

vibechat:
  room:
    base-url: https://CoreVibeChatrooms.com
    code-length: 8
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080
      - http://127.0.0.1:3000
      - http://127.0.0.1:8080
  email:
    smtp:
      host: 127.0.0.1
      port: 1025
      username: toreythegizzler@pm.me
      password: FTBGxYxABQPh4MArikvsyw
      security: STARTTLS
    # Enable email sending and verification for production
    enabled: true
    verification:
      enabled: true
